name: mtg_fire_env
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9.23
  - numpy
  - pandas
  - rasterio
  - rioxarray
  - matplotlib
  - joblib
  - notebook
  - pip
  - pip:
    - torch
    - segmentation-models-pytorch